# Numpy
!pip install numpy

In [3]:
import numpy as np

# Array type & Dim
a = np.array(18)
type(a)

In [7]:
#zero dimensional array
b = np.array(10)
b.ndim

0

In [8]:
#1D array
c = np.array([10,20,30])
c.ndim

1

In [35]:
#2D array
#By default it will run only last line only. to run all linees give print command
d = np.array([[10,20,30]])
print(d.ndim)
e = np.array([[[1,2,3,4,5,6]]])
print(e.ndim)

2
3


# slicing
a = np.array([[1,2,3],[4,5,6]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a[0,0]

1

In [14]:
a[0,1:]

array([2, 3])

In [15]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [19]:
a[1,1]

5

In [24]:
a[[0,1],[1,2]]

array([2, 6])

In [21]:
a[0,1]

2

In [30]:
a[[0,1],[0,2]]
#while extracting randomly any values in 2D data first give row numbers and then in second bracket give colomun numbers

array([1, 6])

In [25]:
a[0,0]

1

In [26]:
a[1,2]

6

# Putting array in differnt Data type
a = np.array([10,23,43,15,77], dtype = 'float')
print(a.dtype)
a

In [40]:
#other ways to create array
#1 arrange. arranging 1 to 11 numbers with step 2
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [42]:
#2 linspace. it evenly disttribute numbers
b = np.linspace(1,5,6,15, retstep=True)
b

(array([1. , 1.8, 2.6, 3.4, 4.2, 5. ]), 0.8)

In [45]:
#3 Random. to get random values in given structure
d = np.random.rand(5,5)
d

array([[0.9288385 , 0.88748593, 0.67021738, 0.84667814, 0.02876812],
       [0.22613768, 0.89820824, 0.1521905 , 0.24150229, 0.38139219],
       [0.10819728, 0.02413508, 0.67902882, 0.86657408, 0.95014348],
       [0.21761554, 0.11741859, 0.38098885, 0.65721446, 0.13052125],
       [0.9633643 , 0.33707779, 0.50325392, 0.03031167, 0.26614925]])

In [48]:
r = np.random.randint(5, size = 10)
r
#it exludes higest value we have given. here ut is 5

array([1, 4, 0, 0, 2, 2, 0, 3, 0, 4])

In [50]:
# slicing and indexing of arrays
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

# reshaping

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a = np.random.rand(5,2)

In [53]:
a

array([[0.97436144, 0.35168807],
       [0.88348364, 0.70961966],
       [0.84750215, 0.73061987],
       [0.19485536, 0.45085867],
       [0.77297359, 0.10012754]])

In [54]:
a.reshape(2,5)

array([[0.97436144, 0.35168807, 0.88348364, 0.70961966, 0.84750215],
       [0.73061987, 0.19485536, 0.45085867, 0.77297359, 0.10012754]])

In [56]:
a.var()
#variance calculation

0.08386553815064261

In [57]:
a.min()
#minimum value

0.1001275374365167

In [58]:
a.mean()

0.601608998327716

In [59]:
a.reshape(5,-1)
#-1 will directly consider other number

array([[0.97436144, 0.35168807],
       [0.88348364, 0.70961966],
       [0.84750215, 0.73061987],
       [0.19485536, 0.45085867],
       [0.77297359, 0.10012754]])

# Aggregate Functions

In [60]:
a

array([[0.97436144, 0.35168807],
       [0.88348364, 0.70961966],
       [0.84750215, 0.73061987],
       [0.19485536, 0.45085867],
       [0.77297359, 0.10012754]])

In [61]:
a.min()

0.1001275374365167

In [62]:
a.std()

0.28959547329100743

In [63]:
a.var()

0.08386553815064261

# Stacking

In [64]:
a = np.array([1,2,3,4,56,6])
b = np.array([9,8,7,6,5,89])

In [65]:
np.hstack([a,b])

array([ 1,  2,  3,  4, 56,  6,  9,  8,  7,  6,  5, 89])

In [66]:
np.vstack([a,b])

array([[ 1,  2,  3,  4, 56,  6],
       [ 9,  8,  7,  6,  5, 89]])